source ‘https://github.com/M00H00/components.git’
source ‘https://github.com/CocoaPods/specs.git’

use_frameworks!

platform :ios, '8.0'

target 'testComponents' do
  pod 'waterflow',

    
  end
end
